from app.models.task import (
    ActivityType,
    PreferredTimeOfDay,
    TaskCategory,
    TaskWorkspace,
)

CATEGORY_KEYWORDS: dict[TaskCategory, tuple[str, ...]] = {
    TaskCategory.work: (
        "trabajo",
        "cliente",
        "reunión",
        "reunion",
        "informe",
        "proyecto",
        "correo",
        "presentación",
        "presentacion",
    ),
    TaskCategory.study: (
        "estudiar",
        "estudio",
        "examen",
        "prueba",
        "curso",
        "clase",
        "tarea",
        "aprender",
    ),
    TaskCategory.personal: (
        "familia",
        "amigo",
        "cumpleaños",
        "cumpleanos",
        "casa",
        "personal",
    ),
    TaskCategory.health: (
        "médico",
        "medico",
        "doctor",
        "dentista",
        "ejercicio",
        "gimnasio",
        "salud",
        "medicamento",
    ),
    TaskCategory.errands: (
        "comprar",
        "supermercado",
        "banco",
        "pagar",
        "trámite",
        "tramite",
        "retirar",
        "buscar",
    ),
}

ACTIVITY_TYPE_KEYWORDS: dict[
    ActivityType,
    tuple[str, ...],
] = {
    ActivityType.deep_work: (
        "analizar",
        "análisis",
        "analisis",
        "desarrollar",
        "programar",
        "investigar",
        "informe",
        "presentación",
        "presentacion",
        "propuesta",
    ),
    ActivityType.meeting: (
        "reunión",
        "reunion",
        "meeting",
        "llamada",
        "videollamada",
    ),
    ActivityType.administrative: (
        "correo",
        "correos",
        "responder",
        "documentar",
        "administrativo",
        "administrativa",
    ),
    ActivityType.exercise: (
        "ejercicio",
        "gimnasio",
        "yoga",
        "correr",
        "caminar",
        "entrenar",
    ),
    ActivityType.errand: (
        "comprar",
        "supermercado",
        "banco",
        "pagar",
        "trámite",
        "tramite",
        "retirar",
        "buscar",
    ),
    ActivityType.study: (
        "estudiar",
        "estudio",
        "examen",
        "prueba",
        "curso",
        "clase",
        "aprender",
    ),
    ActivityType.routine: (
        "rutina",
        "ordenar",
        "limpiar",
        "organizar casa",
    ),
    ActivityType.rest: (
        "descansar",
        "descanso",
        "pausa",
        "siesta",
    ),
}

WORKSPACE_KEYWORDS: dict[
    TaskWorkspace,
    tuple[str, ...],
] = {
    TaskWorkspace.work: (
        "trabajo",
        "cliente",
        "informe",
        "proyecto",
        "reunión",
        "reunion",
        "correo",
        "correos",
        "propuesta",
        "presentación",
        "presentacion",
    ),
    TaskWorkspace.personal: (
        "personal",
        "familia",
        "casa",
        "gimnasio",
        "yoga",
        "ejercicio",
        "médico",
        "medico",
        "doctor",
        "supermercado",
        "comprar",
        "banco",
        "trámite",
        "tramite",
    ),
}

TIME_OF_DAY_KEYWORDS: dict[
    PreferredTimeOfDay,
    tuple[str, ...],
] = {
    PreferredTimeOfDay.morning: (
        "por la mañana",
        "en la mañana",
        "mañana temprano",
    ),
    PreferredTimeOfDay.afternoon: (
        "por la tarde",
        "en la tarde",
    ),
    PreferredTimeOfDay.evening: (
        "por la noche",
        "en la noche",
        "esta noche",
    ),
}